### ISSUE TITLE
Installation failed at 'node copy-typings.js'

### ISSUE THREAD

**Issue by anthonyborell** [Vheissu/aurelia-typescript-webpack-starter#1]
Followed the installation instructions, tried `npm install` and got the following error.

Any advice would be greatly appreciated.
Cheers

```
$ npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN install Couldn't install optional dependency: Unsupported

> aurelia-typescript-webpack-starter@1.0.0-beta.1.2.2 postinstall D:\source\code\app
> node copy-typings.js

D:\source\code\app\node_modules\safe-mkdir\index.js:30
    if (err.code !== 'EEXIST') throw err
                               ^

Error: ENOENT: no such file or directory, mkdir 'D:\source\code\app\typings\modules'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at mkdirSync (D:\source\code\app\node_modules\safe-mkdir\index.js:28:8)
    at D:\source\code\app\node_modules\safe-mkdir\index.js:21:7
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! aurelia-typescript-webpack-starter@1.0.0-beta.1.2.2 postinstall: `node copy-typings.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aurelia-typescript-webpack-starter@1.0.0-beta.1.2.2 postinstall script 'node copy-typings.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aurelia-typescript-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node copy-typings.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls aurelia-typescript-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\source\code\app\npm-debug.log
```

**Comment by anthonyborell** [comment]
Figured it out after a little head scratching. 

Had to create a 'typings' folder in the root directory. After that 'copy-typings.js' worked with no errors.
